#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	SLOT_MACHINE,
	SLOTS,
	ADD_BUTTON,
	DELETE_BUTTON,
	BET_BUTTON,
	START_BUTTON,
	RESTART_BUTTON,
	QUIT_BUTTON,
	NUM_OF_TYPES
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/